### ISSUE TITLE
Основной этап работы

### ISSUE THREAD

**Issue by alex13sh** [alex13sh/BevyScada#9]
Для MVP нужно чтобы:
- [ ] минимально работал опрос модулей по Modbus #2 
- [ ] Можно было базово настраивать устройства. #7 
- [ ] И чтобы это можно было отобразить в любой UI или даже автоматизировать в NodeRed. А для этого нужно трансляция тэгов в Mqtt #3
